In [2]:
import numpy as np


R = np.array([[-1, -1, -1, -1, 0, -1],
              [-1, -1, -1, 0, -1, 100],
              [-1, -1, -1, 0, -1, -1],
              [-1, 0, 0, -1, 0, -1],
              [0, -1, -1, 0, -1, 100],
              [-1, 0, -1, -1, 0, 100]])

Q = np.zeros_like(R)

alpha = 0.8
gamma = 0.95
n_episodes = 1000


for episode in range(n_episodes):
    state = np.random.randint(0, 6)
    while state != 5:
        action = np.random.choice(np.where(R[state, :] != -1)[0])
        next_state = action
        Q[state, action] = Q[state, action] + alpha * (R[state, action] + gamma * np.max(Q[next_state, :]) - Q[state, action])
        state = next_state


print(Q)


[[ 0  0  0  0 93  0]
 [ 0  0  0 88  0 99]
 [ 0  0  0 88  0  0]
 [ 0 93 83  0 93  0]
 [88  0  0 88  0 99]
 [ 0  0  0  0  0  0]]
